{% set name = "sagemaker-studio-cli" %}
{% set version = "1.0.4" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sagemaker_studio_cli-{{ version }}.tar.gz
  sha256: 9dafef119ca8c14f62bf3bd2ac58221c59dfded48094a3ab97455292306ad144

build:
  entry_points:
    - sagemaker-studio=sagemaker_studio_cli:sagemaker_studio
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - mypy
    - invoke
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.1.3
    - sagemaker-studio >=1.0.0

test:
  imports:
    - sagemaker_studio_cli
  commands:
    - pip check
    - sagemaker-studio --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: CLI to interact with SageMaker Studio
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tejaskash
    - devanshdesai
    - akashg105
